# Generated by Django 3.2.8 on 2021-10-21 08:13

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='artwork.productpreset'),
        ),
    ]
