# Generated by Django 3.2.8 on 2021-10-21 08:56

import artwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20211021_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=artwork.models.product_image_directory_path),
        ),
    ]
